# -- coding: utf-8 --
import os
import sys

sys.path.append(os.path.abspath(os.path.dirname(os.path.abspath(__file__)) + "/../../"))

from proj.console import control as inter

from thirdparty.pic2char import pic2char

inter.echo()
lines = pic2char.charimg("/home/work/gmproj/thirdparty/pic2char/head2.png", 30, 30)
lines[1].append("  姓名：万鹏飞")
lines[3].append("  称号：紫阳刀客")
lines[5].append("  根骨：67  力道：70  身法：55")
lines[6].append("  内功：54  洞察：66  悟性：77")
lines[8].append("  搏击：53  剑法：30  刀法：68")
lines[9].append("  长兵：10  暗器：3   奇门：5")
lines[11].append("  运转心法：奔雷心法")
lines[13].append("  战斗武学：紫阳刀法-阳喜必见  紫阳刀法-阳怒必见")
lines[14].append("            观澜掌法-观水有术  观澜掌法-必观其澜")
lines[15].append("            奔雷心法-迅雷变色")
lines[17].append("  战斗物品：小还丹  金疮药")
lines[18].append("            逍遥散  紫阳丹")
lines[20].append("  角色装备：主手-紫金八卦刀")
lines[21].append("            副手-刚玉指虎")
lines[22].append("            头部-铁斗笠")
lines[23].append("            身体-浑天褂")
lines[24].append("            腿部-布鞋")
lines[26].append("  当前修炼：奔雷心法")
for l in lines:
    inter.echo("".join(l))
inter.echo()
lines = pic2char.charimg("/home/work/gmproj/thirdparty/pic2char/head8.png", 45, 45)
lines[1].append("  姓名：刘旭")
lines[3].append("  称号：北辰派首徒")
lines[5].append("  根骨：58  力道：56  身法：73")
lines[6].append("  内功：66  洞察：68  悟性：79")
lines[8].append("  搏击：20  剑法：73  刀法：25")
lines[9].append("  长兵：8   暗器：39  奇门：41")
lines[11].append("  运转心法：斗转星移")
lines[13].append("  战斗武学：裴将军剑-随风游电  裴将军剑-如龙似虎  裴将军剑-八荒烜赫")
lines[14].append("            西河剑法-一剑动四方  西河剑法-羿射九日落  西河剑法-群帝骖龙翔")
lines[17].append("  战斗物品：小还丹  金疮药")
lines[18].append("            逍遥散  定神汤")
lines[20].append("  角色装备：主手-玉具八面剑")
lines[21].append("            副手-无")
lines[22].append("            头部-白玉簪")
lines[23].append("            身体-鹤氅")
lines[24].append("            腿部-朝天履")
lines[26].append("  当前修炼：西河剑法")
for l in lines:
    inter.echo("".join(l))
inter.echo()
lines = pic2char.charimg("/home/work/gmproj/thirdparty/pic2char/head4.png", 30, 30)
lines[1].append("  姓名：朱佳琳")
lines[3].append("  称号：浣纱门护法")
lines[5].append("  根骨：56  力道：51  身法：80")
lines[6].append("  内功：51  洞察：72  悟性：71")
lines[8].append("  搏击：17  剑法：53  刀法：3")
lines[9].append("  长兵：8   暗器：59  奇门：51")
lines[11].append("  主运心法：越绝书")
lines[12].append("  辅运心法：西子捧心诀")
lines[14].append("  战斗武学：越人歌-搴舟中流 越人歌-乔木有枝")
lines[15].append("            细柳剑法-千条玉 细柳剑法-满城絮")
lines[17].append("  战斗物品：九天风露丸 莲子羹")
lines[18].append("            逍遥散")
lines[20].append("  角色装备：主手-碧玉箫")
lines[21].append("            副手-鱼肠剑")
lines[22].append("            头部-金步摇")
lines[23].append("            身体-百铃裙")
lines[24].append("            腿部-谢公屐")
lines[26].append("  当前修炼：越人歌")
for l in lines:
    inter.echo("".join(l))
